#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://1.117.160.6:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 1.117.160.6:8848
#  application:
#    name: gulimall-coupon
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 7000

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://1.117.160.6:9411/
    discovery-client-enabled: false
    sender:
      type: web
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

