#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://1.117.160.6:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 1.117.160.6:8848
#  application:
#    name: gulimall-ware
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 11000

#异步任务配置
spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50