#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#            uri: lb://gulimall-product
#            predicates:
#              - Host=**.gulimall.com

spring:
  cloud:
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: localhost:8080
        port: 8719

      eager: true
